include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    avoid_classes_with_only_static_members: false
    sort_constructors_first: false
    prefer_double_quotes: true
