// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEhdPC3qbxPyg4Zig7ux8OeGpiYsZGRGE',
    appId: '1:652838435599:web:1152451091b746fa499c7a',
    messagingSenderId: '652838435599',
    projectId: 'climaapp-61faf',
    authDomain: 'climaapp-61faf.firebaseapp.com',
    storageBucket: 'climaapp-61faf.firebasestorage.app',
    measurementId: 'G-6M9FL4KPQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwemWNjtnrRSdC7k3XdDnUECHJ9TEBuUM',
    appId: '1:652838435599:android:7d96b87df365a3e1499c7a',
    messagingSenderId: '652838435599',
    projectId: 'climaapp-61faf',
    storageBucket: 'climaapp-61faf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMRkiApRRVYJkS1a3egVbSgEZOiUPaDyg',
    appId: '1:652838435599:ios:5b38e79263f6aac4499c7a',
    messagingSenderId: '652838435599',
    projectId: 'climaapp-61faf',
    storageBucket: 'climaapp-61faf.firebasestorage.app',
    iosBundleId: 'com.example.jsonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMRkiApRRVYJkS1a3egVbSgEZOiUPaDyg',
    appId: '1:652838435599:ios:5b38e79263f6aac4499c7a',
    messagingSenderId: '652838435599',
    projectId: 'climaapp-61faf',
    storageBucket: 'climaapp-61faf.firebasestorage.app',
    iosBundleId: 'com.example.jsonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEhdPC3qbxPyg4Zig7ux8OeGpiYsZGRGE',
    appId: '1:652838435599:web:26c1e210fb837e86499c7a',
    messagingSenderId: '652838435599',
    projectId: 'climaapp-61faf',
    authDomain: 'climaapp-61faf.firebaseapp.com',
    storageBucket: 'climaapp-61faf.firebasestorage.app',
    measurementId: 'G-C6QYH2KQY5',
  );

}