// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqYCYEbtaPdcNyKLthZD7hR8vb95hZWwk',
    appId: '1:741665840173:web:d23c5c98e05fa5cedf2ca4',
    messagingSenderId: '741665840173',
    projectId: 'simport-plus',
    authDomain: 'simport-plus.firebaseapp.com',
    storageBucket: 'simport-plus.firebasestorage.app',
    measurementId: 'G-7T9RXQWDX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP5xEjRXKWq6f8CnM0z7YfnYUTOx2Cf24',
    appId: '1:741665840173:android:11772fec34b11e62df2ca4',
    messagingSenderId: '741665840173',
    projectId: 'simport-plus',
    storageBucket: 'simport-plus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfc2bSYZqFVCyrdfOiwpH2n0LLRaxmqOg',
    appId: '1:741665840173:ios:275487054d071267df2ca4',
    messagingSenderId: '741665840173',
    projectId: 'simport-plus',
    storageBucket: 'simport-plus.firebasestorage.app',
    iosBundleId: 'com.simport.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfc2bSYZqFVCyrdfOiwpH2n0LLRaxmqOg',
    appId: '1:741665840173:ios:92bfc02d7f43c9f5df2ca4',
    messagingSenderId: '741665840173',
    projectId: 'simport-plus',
    storageBucket: 'simport-plus.firebasestorage.app',
    iosBundleId: 'com.example.jsonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqYCYEbtaPdcNyKLthZD7hR8vb95hZWwk',
    appId: '1:741665840173:web:714fe2eeea37e679df2ca4',
    messagingSenderId: '741665840173',
    projectId: 'simport-plus',
    authDomain: 'simport-plus.firebaseapp.com',
    storageBucket: 'simport-plus.firebasestorage.app',
    measurementId: 'G-3PE0R40P0K',
  );
}
